/*
* Project  : Travelling Salesman Problem implementations
* Authors  : Luigi Frigione, Daniel Carlesso
* IDs      : 2060685, 2088626
* File     : pprofile.h
*/

#include "../array/array.h"
#include "../tsp.h"

typedef enum {
	PP_DUMMY, /* Justo to make the indexes start from 1 */
    PP_RANDOM,
	PP_RANDOM_2OPT,
	PP_RANDOM_TABU_CONST,
	PP_RANDOM_TABU_TRIANG,
	PP_RANDOM_TABU_SQUARE,
	PP_RANDOM_TABU_SAWTOO,
	PP_RANDOM_VNS,

	PP_NEAREST_NEIGHBOR_START_FIRST_NODE,
	PP_NEAREST_NEIGHBOR_START_FIRST_NODE_2OPT,
	PP_NEAREST_NEIGHBOR_START_FIRST_NODE_TABU_CONST,
	PP_NEAREST_NEIGHBOR_START_FIRST_NODE_TABU_TRIANG,
	PP_NEAREST_NEIGHBOR_START_FIRST_NODE_TABU_SQUARE,
	PP_NEAREST_NEIGHBOR_START_FIRST_NODE_TABU_SAWTOO,
	PP_NEAREST_NEIGHBOR_START_FIRST_NODE_VNS,

    PP_NEAREST_NEIGHBOR_START_RANDOM_NODE,
	PP_NEAREST_NEIGHBOR_START_RANDOM_NODE_2OPT,
	PP_NEAREST_NEIGHBOR_START_RANDOM_NODE_TABU_CONST,
	PP_NEAREST_NEIGHBOR_START_RANDOM_NODE_TABU_TRIANG,
	PP_NEAREST_NEIGHBOR_START_RANDOM_NODE_TABU_SQUARE,
	PP_NEAREST_NEIGHBOR_START_RANDOM_NODE_TABU_SAWTOO,
	PP_NEAREST_NEIGHBOR_START_RANDOM_NODE_VNS,

	PP_NEAREST_NEIGHBOR_BEST_START,
	PP_NEAREST_NEIGHBOR_BEST_START_2OPT,
	PP_NEAREST_NEIGHBOR_BEST_START_TABU_CONST,
	PP_NEAREST_NEIGHBOR_BEST_START_TABU_TRIANG,
	PP_NEAREST_NEIGHBOR_BEST_START_TABU_SQUARE,
	PP_NEAREST_NEIGHBOR_BEST_START_TABU_SAWTOO,
	PP_NEAREST_NEIGHBOR_BEST_START_VNS,

	PP___END_HEURISTIC,
	PP___END_EXACT
} PP_ALG;

typedef struct {

	Settings set;
	ArrayDinaInt algs;
    
} PP_CONF;
